name: Rebuild Product Lookups
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'With build debug'
        required: false
        default:  false
#  push:
#    branches:
#      - master
jobs:
  update_maps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true

    - name: mkproductlookup
      run: |
        export MIBHOME=`pwd`
        grep -E '^\.1\.3\.6\.1\.4\.1\.\d+\.' $MIBHOME/EXTRAS/reports/*_oids | \
          cut -s -d, -f1,2 | \
          sed -e 's/::/,/' | \
          cut -d : -f 2 | \
          cut -d , -f 1,3 | \
          grep -v '.0,' | \
          sed -e 's/^\.1\.3\.6\.1\.4\.1\.//' > $MIBHOME/EXTRAS/reports/all_leafs_only

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add --all
        git diff --staged --quiet || git commit -m "Update the OID maps via Github Actions"

    - name: Push changes
      uses: ad-m/github-push-action@master
      if: ${{ github.event_name == 'workflow_dispatch' && ! inputs.debug_enabled }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
#      if: always() && github.event.inputs.debug_enabled
      if: always() && ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
#      with:
#        sudo: true

